# Generated by Django 3.1.7 on 2021-04-04 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'upload_images',
            },
        ),
    ]
